spring.application.name=GraphQL

spring.graphql.cors.allowed-origins=http://localhost:3000
spring.graphql.cors.allowed-methods=GET,POST

spring.datasource.url=jdbc:postgresql://localhost:5432/GraphQL
spring.datasource.username=postgres
spring.datasource.password=2121212q
spring.jpa.hibernate.ddl-auto=update